- name: Longhorn => Install required packages on managers
  become: true
  ansible.builtin.apt:
    pkg:
      - jq
      - open-iscsi
      - cryptsetup

- name: Longhorn => Install required packages on workers
  become: true
  ansible.builtin.apt:
    pkg:
      - jq
      - open-iscsi
      - cryptsetup
  delegate_to: "{{ item }}"
  with_items: "{{ groups['workers'] }}"
  run_once: true # Ensures the task is only run once per worker, even if there are multiple manager nodes.

- name: Longhorn => Load iscsi_tcp module on workers
  become: true
  community.general.modprobe:
    name: iscsi_tcp
    state: present
    persistent: present
  delegate_to: "{{ item }}"
  with_items: "{{ groups['workers'] }}"
  run_once: true

- name: Longhorn => Load dm_crypt module on workers
  become: true
  community.general.modprobe:
    name: dm_crypt
    state: present
    persistent: present
  delegate_to: "{{ item }}"
  with_items: "{{ groups['workers'] }}"
  run_once: true

- name: Longhorn => Add labels to Longhorn nodes
  ansible.builtin.command: kubectl label node {{ item }} longhorn=true --overwrite
  with_items:
    - k8s-worker-1
    - k8s-worker-2
    - k8s-worker-3
  changed_when: true

- name: Install => Create manifest folder
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - ./manifests
    - ./manifests/longhorn

- name: Longhorn => Copy Helm values
  ansible.builtin.copy:
    src: values.yaml
    dest: ~/manifests/longhorn/values.yaml
    mode: "0644"

- name: Longhorn => Add Longhorn repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io

- name: Longhorn => Install Longhorn
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    chart_version: "{{ longhorn_chart_version }}"
    release_namespace: longhorn-system
    create_namespace: true
    wait: true
    values_files:
      - ./manifests/longhorn/values.yaml

- name: Longhorn => Apply the Longhorn ingress route
  kubernetes.core.k8s:
    state: present
    template: "templates/longhorn_ingress.yaml.j2"

- name: Longhorn => Update PiHole DNS
  delegate_to: pihole
  ansible.builtin.lineinfile:
    path: /etc/pihole/custom.list
    line: "{{ traefik_lb_ip }} {{ longhorn_ui_url }}"
