- name: Shared node configuration
  ansible.builtin.import_tasks: config.yml
  tags: common-config

- name: Shared node packages
  ansible.builtin.import_tasks: install.yml
  tags: common-install

- name: ContainerD setup
  ansible.builtin.import_tasks: containerd.yml
  tags: common-containerd

- name: K8S tools setup
  ansible.builtin.import_tasks: k8s-tools.yml
  tags: common-k8s-tools
