- name: Prometheus => Add Prometheus stack repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Prometheus => Create manifest folder
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - ~/manifests
    - ~/manifests/monitoring

- name: Prometheus => Create values file
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - { src: secret.yml.j2, dest: ~/manifests/monitoring/secret.yml }
    - { src: values.yml.j2, dest: ~/manifests/monitoring/values.yml }
    - { src: ingress.yml.j2, dest: ~/manifests/monitoring/ingress.yml }

- name: Create a 'monitoring' namespace
  kubernetes.core.k8s:
    name: monitoring
    api_version: v1
    kind: Namespace
    state: present

- name: Prometheus => Add Grafana secret
  kubernetes.core.k8s:
    src: ~/manifests/monitoring/secret.yml

- name: Prometheus => Install Prometheus stack
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    chart_version: "{{ prometheus_chart_version }}"
    release_namespace: monitoring
    create_namespace: true
    values_files:
      - ./manifests/monitoring/values.yml
    wait: true

- name: Prometheus => Add IngressRoute
  kubernetes.core.k8s:
    src: ~/manifests/monitoring/ingress.yml

- name: PiHole => Update DNS
  delegate_to: pihole
  ansible.builtin.lineinfile:
    path: /etc/pihole/custom.list
    line: "{{ traefik_lb_ip }} {{ grafana_url }}"
