- name: ControlPlane => Get cluster info
  kubernetes.core.k8s_cluster_info:
  register: cluster_info
  ignore_errors: true

- name: ControlPlane => Create cluster with kubeadm
  become: true
  ansible.builtin.shell: |
    kubeadm init --pod-network-cidr="{{ pod_network_cidr }}" \
      --apiserver-advertise-address {{ ansible_default_ipv4.address }}
  register: kubeadm_init
  when: cluster_info is failed
  changed_when: kubeadm_init.rc == 0

- name: ControlPlane => Create join command
  become: true
  ansible.builtin.command: kubeadm token create --print-join-command
  register: print_join_command
  when: kubeadm_init is not skipped
  changed_when: true

- name: ControlPlane => Create cluster_join_command.sh file
  ansible.builtin.copy:
    content: "{{ print_join_command.stdout }}"
    dest: /home/{{ ansible_user }}/cluster_join_command.sh
    mode: "0644"
  when: print_join_command is success and print_join_command is not skipped

- name: ControlPlane => Read cluster_join_command.sh file
  ansible.builtin.slurp:
    src: /home/{{ ansible_user }}/cluster_join_command.sh
  register: join_command_file

- name: ControlPlane => Create kube directory
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    mode: "0755"

- name: ControlPlane => Copy Kubernetes config to kube directory
  become: true
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
    remote_src: true

- name: ControlPlane => Download Kubernetes config
  become: true
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: "{{ lookup('env', 'HOME') }}/.kube/config"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: "0644"
    flat: true
  run_once: true

- name: ControlPlane => Store join command as fact
  ansible.builtin.set_fact:
    join_command: "{{ (join_command_file['content'] | b64decode).strip() }}"
  run_once: true

- name: ControlPlane => Show join command from fact
  ansible.builtin.debug:
    msg: "{{ join_command }}"
  run_once: true
