- name: Install parted
  ansible.builtin.package:
    name: parted
    state: present

- name: Get UUIDs for devices
  ansible.builtin.command: lsblk --noempty --nodeps --json --noheadings --output NAME,UUID,SERIAL
  register: lsblk_json_output
  changed_when: false

- name: Update worker_data_disks with device-to-UUID mapping
  ansible.builtin.set_fact:
    worker_data_disks_updated: >
      {{ worker_data_disks_updated | default([]) +
      [item | combine({
        'uuid': (lsblk_json_output.stdout | from_json).blockdevices | selectattr('serial', 'equalto', item.dev_serial) | map(attribute='uuid') | first,
        'name': (lsblk_json_output.stdout | from_json).blockdevices | selectattr('serial', 'equalto', item.dev_serial) | map(attribute='name') | first
      })]
      }}
  loop: "{{ worker_data_disks }}"

- name: Format partitions
  community.general.filesystem:
    fstype: "{{ item.fstype }}"
    dev: "/dev/{{ item.name }}"
  loop: "{{ worker_data_disks_updated }}"

- name: Mount partitions
  ansible.posix.mount:
    path: "{{ item.mount_path }}"
    src: "UUID={{ item.uuid }}"
    fstype: "{{ item.fstype }}"
    state: mounted
  loop: "{{ worker_data_disks_updated }}"

- name: Reload deamon
  ansible.builtin.systemd_service:
    daemon_reload: true
