- name: Traefik => Add Traefik repo
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: https://traefik.github.io/charts

- name: Traefik => Create manifest folder
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - ~/manifests
    - ~/manifests/traefik

- name: Traefik => Generate dashboard credentials
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      htpasswd -nb {{ traefik_dashboard_usermame }} {{ traefik_dashboard_password }} | openssl base64
    executable: /bin/bash
  register: traefik_dashboard_credentials
  changed_when: true

- name: Traefik => Create manifest files from templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - { src: values.yaml.j2, dest: ~/manifests/traefik/values.yaml }
    - { src: dashboard-secret.yaml.j2, dest: ~/manifests/traefik/dashboard-secret.yaml }
    - { src: dashboard-ingress.yaml.j2, dest: ~/manifests/traefik/dashboard-ingress.yaml }
- name: Traefik => Create manifest files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - { src: default-headers.yaml, dest: ~/manifests/traefik/default-headers.yaml }
    - { src: dashboard-middleware.yaml, dest: ~/manifests/traefik/dashboard-middleware.yaml }
- name: Traefik => Install Traefik
  kubernetes.core.helm:
    name: traefik
    chart_ref: traefik/traefik
    chart_version: "{{ traefik_chart_version }}"
    release_namespace: traefik
    create_namespace: true
    values_files:
      - ./manifests/traefik/values.yaml
    wait: true
  register: traefik_install

- name: Traefik => Apply dashboard manifests
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
  loop:
    - ~/manifests/traefik/dashboard-secret.yaml
    - ~/manifests/traefik/dashboard-middleware.yaml
    - ~/manifests/traefik/dashboard-ingress.yaml

- name: PiHole => Update DNS
  delegate_to: pihole
  ansible.builtin.lineinfile:
    path: /etc/pihole/custom.list
    line: "{{ traefik_lb_ip }} {{ traefik_dashboard_url }}"
